### ISSUE TITLE
Error when running "runTest" command

### ISSUE THREAD

**Issue by zouloux** [Strider-CD/strider-cli#22]
I got an error when using runTest command :
`./npm/bin/strider runTest -l ... -p ... -j project/test -b master -m "Hook" -d`

`Login error { Error: socket hang up
    at createHangUpError (_http_client.js:254:15)
    at Socket.socketOnEnd (_http_client.js:346:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) code: 'ECONNRESET' } undefined`

I got the same using API.

Using strider installed globally from NPM. Any idea ?

**Comment by zouloux** [comment]
Better here : https://github.com/Strider-CD/strider/issues/1008
Sorry for the mess
